version: '3.9'

services:

  nginx:
    build: ./engine
    volumes:
      - ./engine/nginx.conf:/etc/nginx/nginx.conf
      # - ./engine/localhost.crt:/app
      # - ./engine/localhost.key:/app
    ports:
      - 8081:80
    

  irm-service:
    build: ./irm-test
    depends_on:
        - nginx
    
  
