version: '3.9'

services:

  nginx:
    build: ./engine
    volumes:
      - ./engine/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    

  irm-service:
    build: ./irm-test
    network_mode: host
    depends_on:
        - nginx
    
  
